apiVersion: v1
kind: Service
metadata:
  name: qdrant-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6333
    protocol: TCP
    targetPort: 6333
  - name: grpc
    port: 6334
    protocol: TCP
    targetPort: 6334
  selector:
    app: qdrant

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-0
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6333
    protocol: TCP
    targetPort: 6333
  selector:
    statefulset.kubernetes.io/pod-name: qdrant-0

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6333
    protocol: TCP
    targetPort: 6333
  selector:
    statefulset.kubernetes.io/pod-name: qdrant-1

---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-2
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6333
    protocol: TCP
    targetPort: 6333
  selector:
    statefulset.kubernetes.io/pod-name: qdrant-2

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qdrant-nodes
spec:
  rules:
  - host: qdrant-0.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qdrant-0
            port:
              number: 6333
  - host: qdrant-1.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qdrant-1
            port:
              number: 6333
  - host: qdrant-2.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qdrant-2
            port:
              number: 6333
