apiVersion: v1
kind: Service
metadata:
  name: qdrant-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6333
    protocol: TCP
    targetPort: 6333
  - name: grpc
    port: 6334
    protocol: TCP
    targetPort: 6334
  selector:
    app: qdrant
