replicaCount: 3

ingress:
  enabled: true
  hosts:
    # an empty name will create a rule without a host, which routes all
    # port 80 ingress traffic to the service
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          servicePort: 6333

persistence:
  # set size of pvc
  # NB: see https://github.com/qdrant/qdrant-helm/issues/34 for how to resize after creation
  size: 1Gi

# enable rolling update when config values change
updateConfigurationOnChange: true
