## see https://github.com/qdrant/qdrant-helm/blob/main/charts/qdrant/values.yaml

replicaCount: 3

image:
  repository: qdrant/qdrant
  tag: v1.7.3
  useUnprivilegedImage: true

persistence:
  # set size of pvc
  # NB: see https://github.com/qdrant/qdrant-helm/issues/34 for how to resize after creation
  size: 1Gi

# enable rolling update when config values change
updateConfigurationOnChange: true
